### ISSUE TITLE
.Resources 文件夹没有下载 

### ISSUE THREAD

**Issue by allenlzg** [muziing/Py2exe-GUI#54]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Scripts\py2exe-gui.exe\__main__.py", line 4, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\py2exe_gui\__main__.py", line 19, in <module>
    from .Resources import COMPILED_RESOURCES  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'py2exe_gui.Resources'

**Comment by muziing** [comment]
我在 Python 3.12 环境中测试通过 pip 安装时复现了这个问题，确实会丢失 Resources 目录。在PyPI下载 `.tar.gz` 格式的发行文件，里面也是有这个目录的，之前在 3.11 中测试也是正常的。目前还没有找到问题，还需要继续研究一下。

**Comment by muziing** [comment]
定位问题：项目使用 Poetry 构建发布，在 [pyproject.toml](https://github.com/muziing/Py2exe-GUI/blob/35e24cb95b1417f5d8b36ad495014e5f5a3d0aa7/pyproject.toml#L10) 中的配置不当，导致 `.whl` 格式的发行文件中 `Resources` 目录错位。

问题已经在 `0.3.2` 版本中解决，使用 pip 更新即可（`pip install -U py2exe-gui`）。
